name: stroke_outcome
channels:
  - conda-forge
dependencies:
  - jupyterlab=3.2.1
  - matplotlib=3.3.4
  - nodejs=16.12.0
  - numpy=1.21.2
  - pandas=1.3.3
  - pip=21.3.1
  - python=3.8.8
  - scipy==1.7.1
  - statsmodels=0.13.0
